#	LICENSING
#
#       This file is part of WireBrush for Spam project (WB4Spam).
#
#       WB4Spam: An ANSI C is an open source, highly extensible, high performance and 
#       multithread spam filtering platform. It takes concepts from SpamAssassin project
#       improving distinct issues.
#
#       Copyright (C) 2010, by Sing Research Group (http://sing.ei.uvigo.es)
#
#       Wirebrush for Spam is free software; you can redistribute it and/or
#       modify it under the terms of the GNU Lesser General Public License as
#       published by the Free Software Foundation; either version 3 of the
#       License, or (at your option) any later version.
#
#       Wirebrush for Spam is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
#       General Public License for more details.
#
#       You should have received a copy of the GNU Lesser General Public License
#       along with this program.  If not, see <http://www.gnu.org/licenses/>.

CC=gcc -g -O3 -fPIC 
CFLAGS=-c -Wall
all: parse_config

parse_config : fileutils.o hashmap.o iniparser.o string_util.o dictionary.o
	$(CC) $(OPTS) fileutils.o string_util.o dictionary.o iniparser.o hashmap.o -o parse_config 

iniparser.o : 
	$(CC) $(CFLAGS) iniparser.c -o iniparser.o

dictionary.o : 
	$(CC) $(CFLAGS) dictionary.c -o dictionary.o

logger.o:
	$(CC) $(CFLAGS) logger.c -o logger.o 

string_util.o:
	$(CC) $(CFLAGS) string_util.c -o string_util.o

hashmap.o:
	$(CC) $(CFLAGS) hashmap.c -o hashmap.o

fileutils.o:
	$(CC) $(CFLAGS) fileutils.c -o fileutils.o

clean: 
	rm *.o parse_config
